(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph

type path = string

(* Values are read as strings. *)
val from_file: path -> string graph

(* Similarly, we write only a string graph.
 * If necessary, use gmap (to be written by you) to prepare the input graph. *)
val write_file: path -> string graph -> unit

(* Export the int graph into a svg .txt file.
 * nodename can be entered to change the name of the nodes in the svp graph.
 * labelform can be entered to change the form of the label in the svg graph. *)
val export: ?nodename:(id -> path) -> ?labelform:(flow arc -> string) -> path -> int graph -> unit

(* Compute the flow of an arc into a formated string "flow/capacity" given its capacity graph *)
val labelwithcapacity: capacity graph -> flow arc -> string

(* The format of files is compatible with the files generated by:
   https://algorithms.discrete.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)
